In [49]:
import pandas as pd
import numpy as np

In [50]:
unicode_list = []

with open("/content/unicode.unicode", "r", encoding='utf8') as unicode_file:
  for i in unicode_file:
    unicode_list.append(i)

In [51]:
unicode_list

['ယ ခု   လ   တွင်   ပျား ရည်   နှင့်   ပျား ဖ ယောင်း   များ   ကို   စု ဆောင်း   ကြ   သည်   ဟု   ခန့် မှန်း   နိုင်   သည်   \n',
 'အ ခန်း ခ   ထဲ   မှာ   ထည့်   လိုက်   ပါ   \n',
 'ဆ ရာ ကြီး   ဦး စိန်   ၏   မြန် မာ   အ ထက် တန်း   ကျောင်း   မှ   ၉   တန်း   အောင် မြင်   ခဲ့   ပြီး   မင်း လှ   မြို့   နော် မံ   ကျောင်း   မှ   အ လယ် တန်း   ဆ ရာ   ဖြစ်   အောင် မြင်   ခဲ့   ၏   \n',
 'ရှစ် လေး လုံး   လှုပ် ရှား   မှု   တွင်   တက် ကြွ   စွာ   ပါ ဝင်   ခဲ့   သ လို     ဗ မာ   နိုင် ငံ   လုံး   ဆိုင် ရာ   ကျောင်း သား   သ မ ဂ္ဂ   များ   အ ဖွဲ့ ချုပ်   မှာ   လည်း   တက် ကြွ   စွာ   ပါ ဝင်   လှုပ် ရှား   ခဲ့   သည်   \n',
 'ဗြိ တိ သျှ   တပ်   များ   သည်   ဂျ ပန်   များ   ၏   ငါး   ဖမ်း   အိမ်   ၃ ၀ ၀ ၀ ၀ ၀   ခန့်   တွင်   အ လုပ်   လုပ် ကိုင်   နေ   ကြ   ရ   သည်   \n',
 'ဗ မာ   မှာ   လူ   များ စု   ဗ မာ   မျိုး နွယ် စု   ၏   ခေါ်   ရာ တွင်   တ ရား ဝင်   ခေါ်   သော   အ သုံး   ဖြစ်   သည်   \n',
 '၂ ၀   ရာ စု   ၏   ပ ထ မ   ပိုင်း   ရာ စု နှစ်   တ ဝက်   တွင်   အိ န္ဒိ ယ   အ မျိုး သား   ကွန် ဂ ရက်   နှင့်   

In [52]:
zawgyi_list = []

with open("/content/zawgyi.zawgyi", "r", encoding='utf8') as zawgyi_file:
  for i in zawgyi_file:
    zawgyi_list.append(i)

zawgyi_list

['ယ ခု   လ   တြ င္   ပ်ား ရ ည္   ႏ ွ င့္   ပ်ား ဖေ ယာ င္း   မ်ား   ကို   စုေ ဆာ င္း   ၾ က   သ ည္   ဟု   ခ န္ ႔ မွ န္း   ႏ ိ ု င္   သ ည္   \n',
 'အ ခ န္း ခ   ထဲ   မွာ   ထ ည့္   လို က္   ပါ   \n',
 'ဆ ရာ ႀ ကီး   ဦး စိ န္   ၏   ျ မ န္မာ   အ ထ က္တ န္း   ေ က်ာ င္း   မွ   ၉   တ န္း   ေ အာ င္ျ မ င္   ခဲ့   ၿ ပီး   မ င္း လွ   ၿ မိဳ ႕   ေ နာ္မံ   ေ က်ာ င္း   မွ   အ လ ယ္တ န္း   ဆ ရာ   ျ ဖ စ္   ေ အာ င္ျ မ င္   ခဲ့   ၏   \n',
 'ရွ စ္ေ လး လုံး   လ ႈ ပ္ရွား   မ ႈ   တြ င္   တ က္ ႂ ကြ   စြာ   ပါ ဝ င္   ခဲ့   သ လို     ဗ မာ   ႏ ိ ု င္ငံ   လုံး   ဆို င္ရာ   ေ က်ာ င္း သား   သ မ ဂ ၢ   မ်ား   အ ဖြဲ ႕ ခ်ဳ ပ္   မွာ   လ ည္း   တ က္ ႂ ကြ   စြာ   ပါ ဝ င္   လ ႈ ပ္ရွား   ခဲ့   သ ည္   \n',
 'ၿ ဗိ တိ သွ်   တ ပ္   မ်ား   သ ည္   ဂ် ပ န္   မ်ား   ၏   ငါး   ဖ မ္း   အိ မ္   ၃ ၀ ၀ ၀ ၀ ၀   ခ န္ ႔   တြ င္   အ လု ပ္   လု ပ္ကို င္   ေ န   ၾ က   ရ   သ ည္   \n',
 'ဗ မာ   မွာ   လူ   မ်ား စု   ဗ မာ   မ်ိဳး ႏ ြ ယ္စု   ၏   ေ ခ ၚ   ရာ တြ င္   တ ရား ဝ င္   ေ ခ ၚ   ေ သာ   အ သုံး   ျ ဖ စ္   သ ည္   \n',
 '၂ ၀   ရာ စု   ၏   ပ ထ မ   ပို င

In [53]:
unicode_df= pd.DataFrame()
zawgyi_df = pd.DataFrame()

In [54]:
unicode_df['message'] = unicode_list
zawgyi_df['message'] = zawgyi_list

In [55]:
zawgyi_df[0:3]

message
0  ယ ခု   လ   တြ င္   ပ်ား ရ ည္   ႏ ွ င့္   ပ်ား ...
1    အ ခ န္း ခ   ထဲ   မွာ   ထ ည့္   လို က္   ပါ   \n
2  ဆ ရာ ႀ ကီး   ဦး စိ န္   ၏   ျ မ န္မာ   အ ထ က္တ...

In [56]:
unicode_df.shape[0]

11000

In [57]:
unicode_df["label"] = [1] * unicode_df.shape[0]
unicode_df

message  label
0      ယ ခု   လ   တွင်   ပျား ရည်   နှင့်   ပျား ဖ ယေ...      1
1           အ ခန်း ခ   ထဲ   မှာ   ထည့်   လိုက်   ပါ   \n      1
2      ဆ ရာ ကြီး   ဦး စိန်   ၏   မြန် မာ   အ ထက် တန်း...      1
3      ရှစ် လေး လုံး   လှုပ် ရှား   မှု   တွင်   တက် ...      1
4      ဗြိ တိ သျှ   တပ်   များ   သည်   ဂျ ပန်   များ ...      1
...                                                  ...    ...
10995  ယင်း   နောက်   ခ ရီး   အ တော်   ကွာ   မှ   အင်...      1
10996  ထို့ ပြင်   ဗိုလ်   သင် တန်း   နှင့်   စစ်   တ...      1
10997  ဤ   စာ အုပ်   တွင်   လည်း   ထို   ကဲ့ သို့   တ...      1
10998  ထို   သို့   မ   ထင်   မိ   ခဲ့   သ ဖြင့်   သူ...      1
10999  ထို   မှ တစ် ပါး   ငှက်   တို့   သည်   ဟင်း လျ...      1

[11000 rows x 2 columns]

In [58]:
zawgyi_df["label"] = [0] * zawgyi_df.shape[0]
zawgyi_df

message  label
0      ယ ခု   လ   တြ င္   ပ်ား ရ ည္   ႏ ွ င့္   ပ်ား ...      0
1        အ ခ န္း ခ   ထဲ   မွာ   ထ ည့္   လို က္   ပါ   \n      0
2      ဆ ရာ ႀ ကီး   ဦး စိ န္   ၏   ျ မ န္မာ   အ ထ က္တ...      0
3      ရွ စ္ေ လး လုံး   လ ႈ ပ္ရွား   မ ႈ   တြ င္   တ ...      0
4      ၿ ဗိ တိ သွ်   တ ပ္   မ်ား   သ ည္   ဂ် ပ န္   မ...      0
...                                                  ...    ...
10995  ယ င္း   ေ နာ က္   ခ ရီး   အေ တာ္   ကြာ   မွ   ...      0
10996  ထို ႔ ျ ပ င္   ဗို လ္   သ င္တ န္း   ႏ ွ င့္   ...      0
10997  ဤ   စာ အု ပ္   တြ င္   လ ည္း   ထို   ကဲ့ သို ႔...      0
10998  ထို   သို ႔   မ   ထ င္   မိ   ခဲ့   သျ ဖ င့္  ...      0
10999  ထို   မွ တ စ္ပါး   ငွ က္   တို ႔   သ ည္   ဟ င္...      0

[11000 rows x 2 columns]

In [59]:
train_unicode_size = int(unicode_df.shape[0]*0.7)
train_unicode_size

7699

In [60]:
train_unicode = unicode_df.head(train_unicode_size)
train_unicode

message  label
0     ယ ခု   လ   တွင်   ပျား ရည်   နှင့်   ပျား ဖ ယေ...      1
1          အ ခန်း ခ   ထဲ   မှာ   ထည့်   လိုက်   ပါ   \n      1
2     ဆ ရာ ကြီး   ဦး စိန်   ၏   မြန် မာ   အ ထက် တန်း...      1
3     ရှစ် လေး လုံး   လှုပ် ရှား   မှု   တွင်   တက် ...      1
4     ဗြိ တိ သျှ   တပ်   များ   သည်   ဂျ ပန်   များ ...      1
...                                                 ...    ...
7694  ကြယ်   အ များ စု   မှာ   မျက် စိ   သက် သက်   ဖ...      1
7695  နက် တိုင်   ကို   တွယ်   တဲ့   ပင်   လို   ချင...      1
7696  အီ တ လီ   အ လံ   အီ တ လီ   နိုင် ငံ   အီ တ လီ ...      1
7697  ၃ ၇   ဖြောင့် မတ်   သော   သူ   တို့   က     သ ...      1
7698  တ ရုတ်     ကို ရီး ယား   နှင့်   ဂျ ပန်   ယဉ် ...      1

[7699 rows x 2 columns]

In [61]:
test_unicode = unicode_df.tail(unicode_df.shape[0] - train_unicode_size)
test_unicode

message  label
7699                                 မ   ဟုတ်   ဘူး   \n      1
7700                                   မ   သိ   ဘူး   \n      1
7701   နေ ထား ဘူ မိ ဗေ ဒ   သည်   ဖိ အား     တွန်း အား...      1
7702   သော ကြာ   ဂြိုဟ်   သည်   နေ   နှင့်   ဒု တိ ယ ...      1
7703   ၁ ၉ ၅ ၈   ခု နှစ်   စက် တင် ဘာ   ၂ ၆   ရက်   တ...      1
...                                                  ...    ...
10995  ယင်း   နောက်   ခ ရီး   အ တော်   ကွာ   မှ   အင်...      1
10996  ထို့ ပြင်   ဗိုလ်   သင် တန်း   နှင့်   စစ်   တ...      1
10997  ဤ   စာ အုပ်   တွင်   လည်း   ထို   ကဲ့ သို့   တ...      1
10998  ထို   သို့   မ   ထင်   မိ   ခဲ့   သ ဖြင့်   သူ...      1
10999  ထို   မှ တစ် ပါး   ငှက်   တို့   သည်   ဟင်း လျ...      1

[3301 rows x 2 columns]

In [62]:
train_zawgyi_size = int(zawgyi_df.shape[0]*0.7)
train_zawgyi = zawgyi_df.head(train_zawgyi_size)
test_zawgyi = zawgyi_df.tail(zawgyi_df.shape[0] - train_zawgyi_size)
test_zawgyi

message  label
7699                                မ   ဟု တ္   ဘူး   \n      0
7700                                   မ   သိ   ဘူး   \n      0
7701   ေ န ထား ဘူ မိေ ဗ ဒ   သ ည္   ဖိ အား     တြ န္း ...      0
7702   ေ သာ ၾ ကာ   ၿ ဂိဳ ဟ္   သ ည္   ေ န   ႏ ွ င့္   ...      0
7703   ၁ ၉ ၅ ၈   ခု ႏ ွ စ္   စ က္တ င္ဘာ   ၂ ၆   ရ က္ ...      0
...                                                  ...    ...
10995  ယ င္း   ေ နာ က္   ခ ရီး   အေ တာ္   ကြာ   မွ   ...      0
10996  ထို ႔ ျ ပ င္   ဗို လ္   သ င္တ န္း   ႏ ွ င့္   ...      0
10997  ဤ   စာ အု ပ္   တြ င္   လ ည္း   ထို   ကဲ့ သို ႔...      0
10998  ထို   သို ႔   မ   ထ င္   မိ   ခဲ့   သျ ဖ င့္  ...      0
10999  ထို   မွ တ စ္ပါး   ငွ က္   တို ႔   သ ည္   ဟ င္...      0

[3301 rows x 2 columns]

In [63]:
train = pd.concat([train_unicode, train_zawgyi], axis=0)
test = pd.concat([test_unicode, test_zawgyi], axis=0)

In [64]:
train = train.sample(frac=1)
test = test.sample(frac=1)

In [65]:
train

message  label
5694  သ င့္   အေ န နဲ ႔   သ က္ဆို င္ရာ   ေ ပ ၚ လ စီ ...      0
6829  T R S   8 0   M O D E L 1 0 0 L I N E   တွင်  ...      1
5568  ၁ ၇ ၂ ၈   ခု ႏ ွ စ္   တြ င္   အိ ဖ ရိ မ္ခ်ိ မ္...      0
4460  ေ တာ င္း ပ န္   ပါ   တ ယ္     ဒါ   က   ယူ   ထာ...      0
3415  သ စ္ေ တာ အု ပ္   ႀ ကီး   မ်ား   ထူ ထ ပ္   သိ ပ...      0
...                                                 ...    ...
4531  ငါး   တို ႔   ၏   ေ က်ာ က္ျ ဖ စ္ ႐ ု ပ္ ႂ ကြ င...      0
6259  ေ ဆး လိ ပ္   ေ သာ က္   ဖို ႔   ရ ပ္   လို က္  ...      0
3937  တြ င္း ထြ က္   သ တ ၱ ဳ ႐ ိ ု င္း   မ်ား   မွ  ...      0
2367  ၄ ၂   အ ကြောင်း   မူ   ကား     ငါ   သည်   မွတ်...      1
4422  လူျ ဖ စ္ရက်ိဳး န ပ္   ေ စ   သ ည့္   ကိ စ ၥ   မ...      0

[15398 rows x 2 columns]

In [66]:
import re

train['message'] = [i.strip().lower() for i in train['message']]
test['message'] = [i.strip().lower() for i in test['message']]

In [69]:
train['message'] = [re.sub(r"([^\s])", r"\1 ", i) for i in train['message']]
test['message'] = [re.sub(r"([^\s])", r"\1 ", i) for i in test['message']]

In [86]:
from tensorflow.keras.preprocessing.text import Tokenizer

test_sentence = ["I am Harry", "I am Ye Bhone Lin!"]
vocab_size = 6
oov_token = "<OOV>"
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_token)
tokenizer.fit_on_texts(test_sentence)

In [90]:
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'i': 2, 'am': 3, 'harry': 4, 'ye': 5, 'bhone': 6, 'lin': 7}


In [88]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = tokenizer.texts_to_sequences(test_sentence)
print(sequences)

[[2, 3, 4], [2, 3, 5, 1, 1]]


In [89]:
max_length = 3
trunc_type = 'post'

padding = pad_sequences(sequences, maxlen=max_length, truncating=trunc_type,padding='post')
padding

array([[2, 3, 4],
       [2, 3, 5]], dtype=int32)

In [91]:
vocab_size = 500
max_length = 4182
trunc_type='post'        #put needed '0's for max length
oov_tok = "<OOV>"        #out of vocab


tokenizer = Tokenizer(num_words = vocab_size, oov_token = oov_tok)
tokenizer.fit_on_texts(train['message'])
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(train['message'])
padded = pad_sequences(sequences,maxlen=max_length, truncating=trunc_type,padding='post')

In [92]:
import tensorflow as tf
embedding_dim = 64
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length = max_length),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(1000, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [93]:
model.compile(loss='binary_crossentropy', optimizer="adam", metrics=['accuracy'])

In [95]:
epochs = 10
history = model.fit(padded, np.array(train['label']), epochs=epochs, verbose=2)

Epoch 1/10
482/482 - 17s - 35ms/step - accuracy: 0.4956 - loss: 0.6932
Epoch 2/10
482/482 - 20s - 42ms/step - accuracy: 0.4966 - loss: 0.6932
Epoch 3/10
482/482 - 21s - 43ms/step - accuracy: 0.4908 - loss: 0.6932
Epoch 4/10
482/482 - 17s - 35ms/step - accuracy: 0.4999 - loss: 0.6932
Epoch 5/10
482/482 - 17s - 35ms/step - accuracy: 0.5009 - loss: 0.6932
Epoch 6/10
482/482 - 20s - 42ms/step - accuracy: 0.4981 - loss: 0.6932
Epoch 7/10
482/482 - 20s - 42ms/step - accuracy: 0.5012 - loss: 0.6932
Epoch 8/10
482/482 - 17s - 35ms/step - accuracy: 0.4982 - loss: 0.6932
Epoch 9/10
482/482 - 21s - 43ms/step - accuracy: 0.4895 - loss: 0.6932
Epoch 10/10
482/482 - 20s - 42ms/step - accuracy: 0.4966 - loss: 0.6932


In [96]:
testing_sequences = tokenizer.texts_to_sequences(test['message'])
testing_padded = pad_sequences(testing_sequences,maxlen=max_length, truncating=trunc_type,padding='post')

In [97]:
y_predict = model.predict(testing_padded)

207/207 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step


In [98]:
y_predict

array([[0.5006085],
       [0.5006085],
       [0.5006085],
       ...,
       [0.5006085],
       [0.5006085],
       [0.5006085]], dtype=float32)

In [100]:
y_pred = []
threshold = 0.5
for i in y_predict:
  current_val = i[0]
  if current_val >= threshold:
    y_pred.append(1)
  else:
    y_pred.append(0)

In [102]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['label'],y_pred)
print('confusion_matrix')
print(confusion_matrix)

confusion_matrix
[[   0 3301]
 [   0 3301]]


In [103]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
ans = y_pred
print('Accuracy Score',accuracy_score(test['label'],ans)*100,'%')
print('Precision Macro Score',precision_score(test['label'],ans,average = 'macro')*100,'%')
print('Recall_Score',recall_score(test['label'],ans, average = 'macro')*100,'%')
print('F1_Score',f1_score(test['label'],ans, average = 'macro')*100,'%')

Accuracy Score 50.0 %
Precision Macro Score 25.0 %
Recall_Score 50.0 %
F1_Score 33.33333333333333 %


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
